<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'سوالات Form ارائه',
	'heading' => 'ارائه فرم جدید',
	'success_redirect' => '%d8%b5%d9%81%d8%ad%d9%87-%d8%a7%d8%b5%d9%84%db%8c.html',
	'resources' => array(
		'checkbox_checked' => 'علامت‌دار',
		'checkbox_unchecked' => 'بی‌علامت',
		'submitted_from' => 'فرم از وب‌سایت زیر دریافت شد: ‎%s',
		'submitted_by' => 'آدرس IP بازدیدکننده: ‎%s',
		'too_many_submissions' => 'اخیراً تعداد موارد ارائه شده از این IP خیلی زیاد بوده است',
		'failed_to_send_email' => 'ارسال ایمیل ناموفق بود',
		'invalid_reCAPTCHA_private_key' => 'کلید خصوصی reCAPTCHA نامعتبر است.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'قسمت ‎\'%s\'‎ ناشناخته است.‎',
		'invalid_form_config' => 'پیکربندی قسمت \'‎%s\' نامعتبر است.',
		'unknown_method' => 'روش درخواست سرور ناشناخته'
	),
	'email' => array(
		'from' => 'arshiakh2468@gmail.com',
		'to' => 'arshiakh2468@gmail.com'
	),
	'fields' => array(
		'custom_U289' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'نام',
			'required' => true,
			'errors' => array(
				'required' => 'قسمت \'نام\' مورد نیاز است.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'ایمیل',
			'required' => true,
			'errors' => array(
				'required' => 'قسمت \'ایمیل\' مورد نیاز است.',
				'format' => 'ایمیل در قسمت \'ایمیل\' نامعتبر است.'
			)
		),
		'custom_U299' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'پیام',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
